### ISSUE TITLE
change the font 

### ISSUE THREAD

**Issue by himanshubarik** [himanshubarik/college-club-website#1]

**Comment by dschandrasekara** [comment]
Hi @himanshubarik can you give more detail about issue ?

**Comment by shanicesmith98** [comment]
Mind if I try changing the font?

**Comment by himanshubarik** [comment]
Yes if the code needs to be changed then change it i will be grateful

**Comment by veridiem** [comment]
Hi, I want to help with that.

**Comment by himanshubarik** [comment]
fixed
